# PROCESSING PARAM.S
proc:
  # number of cores to use
  cpu_cores: 2
  

# DATA INFORMATION
data:
  # main data folder - where everything data-related is located
  base_path: '/content/data'
  
  # preprocessed data folder - where all the byproducts of the pipeline are stored
  preproc_base_path: '/content/data/processed'
  
  # location where the images to be processed with the nnU-Net pipeline are stored
  # (NIfTI files, named following the nnU-Net conventions)
  model_input_path: '/content/data/model_input/'
  
  # location where the mask(s) inferred by the nnU-Net pipeline are stored
  output_path_nii: '/content/data/nnunet_output/'
  
  # name of the subfolder, under each patient folder, where the manual segmentation masks 
  # (from the RTSTRUCT file) are stored
  rt_segmasks_folder_name: "rt_segmasks"
  
  # name of the subfolder, under each patient folder, where the nnU-Net segmentation masks 
  # (inferred by the pipeline, resampled, converted to NRRD) are stored
  pred_segmasks_folder_name: "pred_segmasks"
  

# GENERAL DATASET INFORMATION
dataset:
  # name of the dataset - used to obtain a number of paths (from where to parse/store data and results)
  name: 'nsclc-radiomics'
  
  
# POST-INFERENCE 
post:
  # inferred masks to resample and convert to NRRD (from NIfTI)
  structures_to_export: ["Esophagus", "Heart", "Trachea", "Aorta"]
  

# EVALUATION PHASE
eval:
  # inferred masks to compute the evaluation (Dice Coefficient and Hausdorff Distance) of
  structures_to_eval: ["Heart", "Esophagus"]
  
  # path where to store the evaluation phase results (tabled data)
  results_base_path: "/content/output"
